<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.1" />
    <PackageReference Include="Autofac" Version="8.*" />
    <PackageReference Include="Dapper" Version="2.*" />
    <PackageReference Include="Dapper.Contrib" Version="2.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Findly.Domain\Findly.Domain.csproj" />
    <ProjectReference Include="..\Findly.Application\Findly.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Findly.UnitTests" />
  </ItemGroup>

</Project>
